url: https://y7kim.github.io
baseurl: /hafrate.github.io/
plugins:
  - jekyll-seo-tag
# Site settings
title: Mohammed HAFRATE
email: hafrate@gmail.com
description: "IFRS reporting Power bi query conseil data science profils finance evaluation monte carlo ."


# Team names, titles and social links
people:
- name: EXPERTISE
  pic: 1
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

- name: CREATIVITE
  pic: 2
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

- name: REACTIVITE
  pic: 3
  position: 
  social:
    - title: 
      url: #
    - title: 
      url: #
    - title: 
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket 
    url: 
  - title: github
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
